# Quick syntax check:
# python -c 'import sys, yaml; yaml.dump (yaml.load (sys.stdin), sys.stdout)' <.gitlab-ci.yml

# If things don't seem to work, this can help:
# https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/ci/lint

stages:
  - test
  - deploy

.fedora_install: &fedora_install
  before_script:
    - NM_INSTALL="dnf install -y" ./contrib/fedora/REQUIRED_PACKAGES
    - dnf install -y glibc-langpack-pl
    - locale -a

checkpatch:
  image: fedora:28
  stage: test
  script:
    - dnf install -y git
    - contrib/scripts/checkpatch-feature-branch.sh 2>&1 | tee checkpatch-out.txt
  allow_failure: true
  artifacts:
    when: on_failure
    paths:
      - checkpatch-out.txt

f28_build_autotools:
  <<: *fedora_install
  image: fedora:28
  stage: test
  script:
    - CI=gitlab BUILD_TYPE=autotools contrib/scripts/nm-ci-run.sh
    - mv build/INST/share/gtk-doc/html docs-html
  artifacts:
    expire_in: 1 day
    paths:
      - docs-html

f28_build_meson:
  <<: *fedora_install
  image: fedora:28
  stage: test
  script:
    - CI=gitlab BUILD_TYPE=meson contrib/scripts/nm-ci-run.sh

f28_rpm_autotools_dbg:
  <<: *fedora_install
  image: fedora:28
  stage: test
  script:
    - ./contrib/fedora/rpm/build_clean.sh -g -w crypto_gnutls -w debug -w iwd -w test

f28_rpm_meson_dbg:
  <<: *fedora_install
  image: fedora:28
  stage: test
  script:
    - ./contrib/fedora/rpm/build_clean.sh -g -w crypto_gnutls -w debug -w iwd -w meson -w test

pages:
  stage: deploy
  dependencies:
    - f28_build_autotools
  script:
    - mv docs-html public
  artifacts:
    expire_in: 20 days
    paths:
      - public
  only:
    - master
